const doctorsData = [
  {
    id: 1,
    name: "Dr. Sneha Iyer",
    specialty: "Neurology",
    experience: 10,
    rating: 4.7,
    availability: "Mon-Fri",
    image: "/images/d1.png",
    qualification: "MBBS, DM Neurology",
    schedule: {
      "2025-10-06": ["10:00", "11:00", "14:00"],
      "2025-10-07": ["09:00", "12:00"],
    },
    tagline: "Healing kidneys, one beat at a time."

  },
  {
    id: 2,
    name: "Dr. Shreya Gupta",
    specialty: "Gynecology",
    experience: 13,
    rating: 4.8,
    availability: "Mon-Sat",
    image: "/images/d2.png",
    qualification: "MBBS, MD Gynecology",
    schedule: {
      "2025-10-06": ["10:00", "13:00"],
      "2025-10-07": ["09:00", "15:00"],
    },
  },
  {
    id: 3,
    name: "Dr. Varun Mishra",
    specialty: "Dermatology",
    experience: 9,
    rating: 4.5,
    availability: "Mon-Fri",
    image: "/images/d3.png",
    qualification: "MBBS, MD Dermatology",
  },
  {
    id: 4,
    name: "Dr. Parag Kulkarni",
    specialty: "Urology",
    experience: 8,
    rating: 4.4,
    availability: "Mon-Fri",
    image: "/images/d4.png",
    qualification: "MBBS, MCh Urology",
  },
  {
    id: 5,
    name: "Dr. Sanjay Mehta",
    specialty: "Orthopedics",
    experience: 14,
    rating: 4.8,
    availability: "Mon-Sat",
    image: "/images/d5.png",
    qualification: "MBBS, MS Orthopedics",
  },
  {
    id: 6,
    name: "Dr. Sunita Chawla",
    specialty: "Nephrology",
    experience: 9,
    rating: 4.5,
    availability: "Tue-Fri",
    image: "/images/d6.png",
    qualification: "MBBS, DM Nephrology",
  },
  {
    id: 7,
    name: "Dr. Kavita Desai",
    specialty: "Cardiology",
    experience: 15,
    rating: 4.9,
    availability: "Mon-Sat",
    image: "/images/d7.png",
    qualification: "MBBS, MD Cardiology",
  },
  {
    id: 8,
    name: "Dr. Rohit Suresh",
    specialty: "Psychiatry",
    experience: 8,
    rating: 4.5,
    availability: "Mon-Fri",
    image: "/images/d8.png",
    qualification: "MBBS, MD Psychiatry",
  },
  {
    id: 9,
    name: "Dr. Rohit Malhotra",
    specialty: "Dermatology",
    experience: 10,
    rating: 4.7,
    availability: "Mon-Sat",
    image: "/images/d9.png",
    qualification: "MBBS, MD Dermatology",
  },
  {
    id: 10,
    name: "Dr. Prakash Malviya",
    specialty: "Dentistry",
    experience: 7,
    rating: 4.4,
    availability: "Wed-Sat",
    image: "/images/d10.png",
    qualification: "BDS, MDS Dentistry",
  },
  {
    id: 11,
    name: "Dr. Shantanu Mukherjee",
    specialty: "General Surgery",
    experience: 15,
    rating: 4.9,
    availability: "Mon-Sat",
    image: "/images/d11.png",
    qualification: "MBBS, MS General Surgery",
  },
  {
    id: 12,
    name: "Dr. Neha Kulkarni",
    specialty: "Pediatrics",
    experience: 8,
    rating: 4.5,
    availability: "Mon-Fri",
    image: "/images/d12.png",
    qualification: "MBBS, MD Pediatrics",
  },
  {
    id: 13,
    name: "Dr. Jyoti Menon",
    specialty: "Psychiatry",
    experience: 10,
    rating: 4.6,
    availability: "Tue-Thu",
    image: "/images/d13.png",
    qualification: "MBBS, MD Psychiatry",
  },
  {
    id: 14,
    name: "Dr. Mohan Yadav",
    specialty: "Nephrology",
    experience: 8,
    rating: 4.4,
    availability: "Mon-Fri",
    image: "/images/d14.png",
    qualification: "MBBS, DM Nephrology",
  },
  {
    id: 15,
    name: "Dr. Meera Bhandari",
    specialty: "Neurology",
    experience: 7,
    rating: 4.4,
    availability: "Wed-Sat",
    image: "/images/d15.png",
    qualification: "MBBS, DM Neurology",
  },
  {
    id: 16,
    name: "Dr. Naveen Joshi",
    specialty: "Gynecology",
    experience: 9,
    rating: 4.5,
    availability: "Tue-Fri",
    image: "/images/d16.png",
    qualification: "MBBS, MD Gynecology",
  },
  {
    id: 17,
    name: "Dr. Harish Khanna",
    specialty: "Dentistry",
    experience: 10,
    rating: 4.6,
    availability: "Tue-Fri",
    image: "/images/d17.png",
    qualification: "BDS, MDS Dentistry",
  },
  {
    id: 18,
    name: "Dr. Rajeev Nair",
    specialty: "Cardiology",
    experience: 11,
    rating: 4.5,
    availability: "Wed-Fri",
    image: "/images/d18.png",
    qualification: "MBBS, MD Cardiology",
  },
  {
    id: 19,
    name: "Dr. Sameer Puri",
    specialty: "Gastroenterology",
    experience: 9,
    rating: 4.5,
    availability: "Mon-Fri",
    image: "/images/d19.png",
    qualification: "MBBS, DM Gastroenterology",
  },
  {
    id: 20,
    name: "Dr. Ajay Saxena",
    specialty: "Allergy & Immunology",
    experience: 8,
    rating: 4.5,
    availability: "Mon-Fri",
    image: "/images/d20.png",
    qualification: "MBBS, MD Allergy & Immunology",
  },
  {
    id: 21,
    name: "Dr. Rakesh Saini",
    specialty: "Gastroenterology",
    experience: 14,
    rating: 4.8,
    availability: "Mon-Sat",
    image: "/images/d21.png",
    qualification: "MBBS, DM Gastroenterology",
  },
  {
    id: 22,
    name: "Dr. Ramesh Patel",
    specialty: "Neurology",
    experience: 8,
    rating: 4.5,
    availability: "Tue-Thu",
    image: "/images/d22.png",
    qualification: "MBBS, DM Neurology",
  },
  {
    id: 23,
    name: "Dr. Pankaj Tiwari",
    specialty: "Orthopedics",
    experience: 11,
    rating: 4.6,
    availability: "Wed-Sat",
    image: "/images/d23.png",
    qualification: "MBBS, MS Orthopedics",
  },
  {
    id: 24,
    name: "Dr. Ritu Sinha",
    specialty: "Dentistry",
    experience: 8,
    rating: 4.5,
    availability: "Mon-Fri",
    image: "/images/d24.png",
    qualification: "BDS, MDS Dentistry",
  },
  {
    id: 25,
    name: "Dr. Priya Menon",
    specialty: "Pediatrics",
    experience: 10,
    rating: 4.7,
    availability: "Mon-Sat",
    image: "/images/d25.png",
    qualification: "MBBS, MD Pediatrics",
  },
  {
    id: 26,
    name: "Dr. Ayesha Sharma",
    specialty: "Cardiology",
    experience: 12,
    rating: 4.8,
    availability: "Mon-Fri",
    image: "/images/d26.png",
    qualification: "MBBS, MD Cardiology",
  },
  {
    id: 27,
    name: "Dr. Isha Bansal",
    specialty: "Gynecology",
    experience: 11,
    rating: 4.7,
    availability: "Mon-Fri",
    image: "/images/d27.png",
    qualification: "MBBS, MD Gynecology",
  },
  {
    id: 28,
    name: "Dr. Rohan Chatterjee",
    specialty: "Allergy & Immunology",
    experience: 7,
    rating: 4.4,
    availability: "Mon-Fri",
    image: "/images/d28.png",
    qualification: "MBBS, MD Allergy & Immunology",
  },
  {
    id: 29,
    name: "Dr. Anita Reddy",
    specialty: "Orthopedics",
    experience: 9,
    rating: 4.5,
    availability: "Tue-Fri",
    image: "/images/d29.png",
    qualification: "MBBS, MS Orthopedics",
  },
  {
    id: 30,
    name: "Dr. Anita Mehra",
    specialty: "Dentistry",
    experience: 12,
    rating: 4.8,
    availability: "Mon-Sat",
    image: "/images/d30.png",
    qualification: "BDS, MDS Dentistry",
  },
  {
    id: 31,
    name: "Dr. Suman Rawat",
    specialty: "Urology",
    experience: 9,
    rating: 4.5,
    availability: "Tue-Thu",
    image: "/images/d31.png",
    qualification: "MBBS, MCh Urology",
  },
  {
    id: 32,
    name: "Dr. Karan Bhatt",
    specialty: "Nephrology",
    experience: 11,
    rating: 4.7,
    availability: "Mon-Sat",
    image: "/images/d32.png",
    qualification: "MBBS, DM Nephrology",
  },
  {
    id: 33,
    name: "Dr. Manish Agarwal",
    specialty: "Pediatrics",
    experience: 7,
    rating: 4.4,
    availability: "Mon-Fri",
    image: "/images/d33.png",
    qualification: "MBBS, MD Pediatrics",
  },
  {
    id: 34,
    name: "Dr. Vandana Joshi",
    specialty: "Gastroenterology",
    experience: 7,
    rating: 4.4,
    availability: "Wed-Sat",
    image: "/images/d34.png",
    qualification: "MBBS, DM Gastroenterology",
  },
  {
    id: 35,
    name: "Dr. Abhishek Verma",
    specialty: "Psychiatry",
    experience: 12,
    rating: 4.8,
    availability: "Mon-Fri",
    image: "/images/d35.png",
    qualification: "MBBS, MD Psychiatry",
  },
  {
    id: 36,
    name: "Dr. Shruti Sen",
    specialty: "Dermatology",
    experience: 12,
    rating: 4.8,
    availability: "Tue-Fri",
    image: "/images/d36.png",
    qualification: "MBBS, MD Dermatology",
  },
  {
    id: 37,
    name: "Dr. Anjali Kaul",
    specialty: "Gastroenterology",
    experience: 11,
    rating: 4.6,
    availability: "Tue-Fri",
    image: "/images/d37.png",
    qualification: "MBBS, DM Gastroenterology",
  },
  {
    id: 38,
    name: "Dr. Shalini Verma",
    specialty: "Orthopedics",
    experience: 8,
    rating: 4.4,
    availability: "Mon-Fri",
    image: "/images/d38.png",
    qualification: "MBBS, MS Orthopedics",

  },
  {
    id: 39,
    name: "Dr. Harpreet Singh",
    specialty: "Urology",
    experience: 12,
    rating: 4.8,
    availability: "Mon-Fri",
    image: "/images/d39.png",
    qualification: "MBBS, MCh Urology",
  },
  {
    id: 40,
    name: "Dr. Pooja Saxena",
    specialty: "Gynecology",
    experience: 7,
    rating: 4.4,
    availability: "Wed-Sat",
    image: "/images/d40.png",
    qualification: "MBBS, MD Gynecology",
  },
  {
    id: 41,
    name: "Dr. Arvind Sethi",
    specialty: "Neurology",
    experience: 13,
    rating: 4.8,
    availability: "Mon-Sat",
    image: "/images/d41.png",
    qualification: "MBBS, DM Neurology",
  },
  {
    id: 42,
    name: "Dr. Nisha Kapoor",
    specialty: "Dermatology",
    experience: 6,
    rating: 4.3,
    availability: "Wed-Sat",
    image: "/images/d42.png",
    qualification: "MBBS, MD Dermatology",
  },
  {
    id: 43,
    name: "Dr. Priyanka Das",
    specialty: "Allergy & Immunology",
    experience: 10,
    rating: 4.6,
    availability: "Tue-Thu",
    image: "/images/d43.png",
    qualification: "MBBS, MD Allergy & Immunology",
  },
  {
    id: 44,
    name: "Dr. Mrinal Agnihotri",
    specialty: "Cardiology",
    experience: 9,
    rating: 4.6,
    availability: "Tue-Thu",
    image: "/images/d44.png",
    qualification: "MBBS, MD Cardiology",
  },
  {
    id: 45,
    name: "Dr. Ashok Gupta",
    specialty: "Pediatrics",
    experience: 6,
    rating: 4.3,
    availability: "Tue-Fri",
    image: "/images/d45.png",
    qualification: "MBBS, MD Pediatrics",
  },
];

export default doctorsData;
